# Generated by Django 5.0.2 on 2024-05-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
